---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Kazuki Yamamoto.
--- DateTime: 2026/05/16
---

local pretty = require("pl.pretty")
local tablex = require("pl.tablex")
local stringx = require("pl.stringx")
local List = require("pl.List")
local xrange = require("pl.List").range

local stringify = require("pandoc.utils").stringify

local debug = require("pandocker.utils").debug
local MESSAGE = "[ lua ] insert a table from %s"
local FILE_NOT_FOUND = "[ lua ] %s: file not found"

local empty_attr = { "", {}, {} }
local empty_row = function()
    return { empty_attr, {} }
end

local table_template = [==[
|   |   |
|---|---|
| a | b |
]==]

local my_table = pandoc.read(table_template, "markdown").blocks[1]

function deny_2_15()
    if tostring(PANDOC_VERSION) == "2.15" then
        debug("[ Lua ] " .. PANDOC_SCRIPT_FILE .. ": Pandoc version 2.15 is not supported. Bypassing.")
        return
    end
end

function CodeBlock(el)
    deny_2_15() -- deny 2.15 and return immediately

    if FORMAT == "docx" or FORMAT == "native" then
        local linefrom = tonumber(el.attributes["from"]) or 1
        if linefrom < 1 then
            linefrom = 1
        end
        local lineto = tonumber(el.attributes["to"]) or -1
        local nrs = pandoc.CodeBlock(stringx.join("\n", List().range(linefrom, lineto)), empty_attr)
        local table = my_table:clone()
        local nrs_div = pandoc.Div({ nrs }, { "", { "plain" }, {} })
        local cbk_div = pandoc.Div({ el }, el.attr)
        cbk_div["attributes"]["custom-style"] = "Source Code"
        nrs_div["attributes"]["custom-style"] = "Source Code"

        table.colspecs = { { pandoc.AlignRight, 0.05 }, { pandoc.AlignLeft, 1.0 } }
        table.head = pandoc.TableHead {}
        table.bodies[1].body[1].cells[1].contents = { nrs_div }
        table.bodies[1].body[1].cells[2].contents = { cbk_div }
        --pretty.dump(table.bodies[1].body[1].cells[1].contents)
        --pretty.dump(table.bodies)
        --[[
        debug(linefrom)
        debug(lineto)
        debug(stringx.join(",", List().range(linefrom, lineto)))
        ]]
        return table
    end
end

