--[[
Generated by EmmyLua(https://github.com/EmmyLua)
Created by yamamoto.
DateTime: 2026/08/05 17:34

# docx-tabularize-figures.lua

Converts list of (inline) images to a subfigure table.
Co-work with pandoc-crossref filter (this must apply before crossref).
The Div must be figurediv class.
See also pandoc-crossref help page for subfigures: https://lierdakil.github.io/pandoc-crossref/#subfigures

## Syntax

:::{#fig:svg .figurediv col=2}

![another SVG file1](images/bitfield.svg){#fig:svg-1 width=73mm}
![another SVG file5](images/bitfield.svg){#fig:svg-5 width=73mm}
![another SVG file6](images/bitfield.svg){#fig:svg-6 width=73mm}

<Image caption>
:::

- col: number of subfigure columns. default is 1

]]

--local pretty = require("pl.pretty")
local pList = require("pl.List")

local stringify = require("pandoc.utils").stringify
local debug = require("pandocker.utils").debug
local deny_2_15 = require("pandocker.utils").deny_2_15
local MESSAGE = "[ lua ] Tabularize figures"

local padding_space = pandoc.Space()
local table_template = [==[
| table |
|-------|
| cell  |

Table: caption
]==]

local my_table = pandoc.read(table_template, "markdown").blocks[1]

local empty_attr = { "", {}, {} }

local ALIGN = { ["D"] = pandoc.AlignDefault,
                ["L"] = pandoc.AlignLeft,
                ["C"] = pandoc.AlignCenter,
                ["R"] = pandoc.AlignRight
}

local function get_cell(c)
    return { attr = empty_attr,
             alignment = pandoc.AlignDefault,
             row_span = 1,
             col_span = 1,
             contents = pandoc.List({ c }) } -- Cell
end

local function get_row(t)
    local row = pandoc.List({})
    for _, v in ipairs(t) do
        row:insert(get_cell(v))
    end
    return { empty_attr, row }
end

if FORMAT == "docx" or FORMAT == "native" or FORMAT == "gfm" then
    local image_list = pandoc.List({})
    local function tagging(img)
        --debug(tostring(img.attr))
        if not img.classes:includes "figurediv" then
            img.classes:insert "figurediv"
        end
        image_list:insert(img)
    end

    local function figure(fig)
        local function f2i(im)
            im.identifier = fig.identifier
            --debug(im.identifier)
            return im
        end
        fig:walk({ Image = f2i })
        --debug(tostring(fig.identifier))
        --pretty.dump(fig.content)
        return fig
    end

    local function figurediv(el)
        deny_2_15()
        if not el.classes:includes "figurediv" then
            return
        end
        debug(MESSAGE)
        local cols = tonumber(el.attributes["col"]) or 1
        local rows = 1
        local ratio = 1 / cols
        local title = el.content[#el.content]
        local table = my_table:clone()

        el.content[#el.content] = {}
        el:walk({ Figure = figure, Image = tagging })
        --debug(#image_list)

        if #image_list % cols ~= 0 then
            for i = 1, (cols - #image_list % cols) do
                image_list:insert(padding_space)
                --debug("padding #" .. i)
            end
        end

        rows = #image_list // cols

        --debug(#image_list .. ", " .. cols .. ", " .. rows)

        local cnt = 1
        local raw_cells = nil
        local row = nil
        local body1 = table.bodies[1]
        body1.body = pandoc.List()
        table.head = pandoc.TableHead({})
        table.colspecs = pandoc.List()
        table.caption = {}
        for i = 1, rows do
            raw_cells = pList(image_list):slice(cnt, cnt + cols)
            row = get_row(raw_cells)
            body1.body:insert(row)
            --pretty.dump(row)
            cnt = cnt + cols
        end

        for i = 1, cols do
            table.colspecs:insert({ ALIGN.D, ratio })
        end

        el.content = { table, title }

        return el

    end

    return { { Div = figurediv } }

end
